Repository vtex-apps/search, pull requests merged in 2020-05, with the labels that each got.

#60 Improve 1.x documentation
  CHANGELOG.md
  docs/Autocomplete.md
  docs/Banner.md
  docs/DidYouMean.md
  docs/README.md
  docs/Suggestions.md
Labels: 1.x

#61 Improve 0.x documentation
  docs/Banner.md
  docs/DidYouMean.md
  docs/README.md
  docs/Suggestions.md
Labels: 0.x

#62 Bump timeout while we're investigating heavy load.
  CHANGELOG.md
  node/index.ts
  node/resolvers/search.ts
  node/service.json
Labels: 0.x

#67 Add Google Analytics config docs
  CHANGELOG.md
  docs/README.md
Labels: V: 1.x

#66 Improve docs for order options
  CHANGELOG.md
  docs/README.md
Labels: V: 0.x

#64 use Link instead of a
  CHANGELOG.md
  react/components/Autocomplete/components/TileList/TileList.tsx
Labels: V: 1.x

#71 Use __unstableProductOriginVtex
  CHANGELOG.md
  docs/Autocomplete.md
  react/components/Autocomplete/index.tsx
Labels: V: 1.x
